//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer3_POC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityClientSecret
    {
        public int Id { get; set; }
        public string Client_Secret { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTimeOffset> Expiration { get; set; }
        public int Client_Id { get; set; }
    
        public virtual IdentityClient IdentityClient { get; set; }
    }
}
