//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer3_POC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdentityClient()
        {
            this.IdentityClientSecrets = new HashSet<IdentityClientSecret>();
        }
    
        public int Id { get; set; }
        public string Client_Id { get; set; }
        public string Client_Name { get; set; }
        public bool Enabled { get; set; }
        public int Flow { get; set; }
        public int AccessTokenLifetime { get; set; }
        public string AccessTokenType { get; set; }
        public string Client_Scope { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdentityClientSecret> IdentityClientSecrets { get; set; }
    }
}
